export default {
  weKnowBalkan: 'We Know the Balkans, Follow us',
  whereToGo: 'Where do you want to go?',
  shop: 'Shop',
  topAttractions: 'Top Attractions',
  hotels: 'Hotels',
  restaurants: 'Restaurants',
  tours: 'Tours',
  transportation: 'Transportation',
  explore: 'Explore',
  dictionary: 'Dictionary',
  interactiveMap: 'Explore all on interactive map',
  mapView: 'Map View',
  navigation: 'Navigation',
  description: 'Description',
  object: 'Object',
  phone: 'Telephone',
  web: 'Web',
  email: 'Email',
  findMoreAbout: 'Find More About ',
  returnToListOf: 'Return to list of ',
  creditPage: 'Credit Page ',
  settingsPage: 'Settings Page ',
  download:'Download',
  removeMaps:'Remove all saved maps'

};
