export default {
  weKnowBalkan: "我們了解巴爾幹，關注我們",
  whereToGo: "你想去哪里",
  shop: "店铺",
  topAttractions: "热门景点",
  hotels: "旅馆",
  restaurants: "饭店",
  tours: "游览",
  transportation: "运输",
  explore: "探索",
  dictionary: "字典",
  interactiveMap: "在互动地图上探索一切",
  mapView: "地图检视",
  navigation: "导航",
  description: "描述",
  object: "目的",
  object: "目的",
  phone: "电话",
  web: "网路",
  email: "电子邮件",
  findMoreAbout: "了解更多 ",
  returnToListOf: "返回列表 ",
  creditPage:"信用页面",
  settingsPage: '设置页面 ',
  download:'下载 ',
  removeMaps:'删除所有保存的地图'
} 